export const ENDPOINTS = [
  "/api/v1/auth/login",
  "/api/v1/auth/register",
  "/api/v1/auth/refresh",
  "/api/v1/auth/recover-password-code",
  "/api/v1/auth/reset-password-code",
  "/api/v1/auth/send-email-activation",
  "/api/v1/auth/send-activation-code",
  "/api/v1/auth/activate",
  "/api/v1/auth/google",
  "/api/v1/auth/activate-code",
  "/api/v1/auth/verify-reset-code",
  "/api/v1/products",
  "/api/v1/categories",
  "/api/v1/promotions/images",
];
