export enum PermissionCode {
  USER_READ = 'user.read',
  USER_CREATE = 'user.create',
  USER_UPDATE = 'user.update',
  USER_DELETE = 'user.delete',
  ROLE_READ = 'role.read',
  ROLE_MANAGE = 'role.manage',
  PRODUCT_READ = 'product.read',
  PRODUCT_CREATE = 'product.create',
  PRODUCT_UPDATE = 'product.update',
  PRODUCT_DELETE = 'product.delete',
  ORDER_READ = 'order.read',
  ORDER_UPDATE = 'order.update',
  ORDER_MANAGE = 'order.manage',
  INVENTORY_MANAGE = 'inventory.manage',
  PROMOTION_MANAGE = 'promotion.manage',
  NOTIFICATION_MANAGE = 'notification.manage',
}
